### ISSUE TITLE
Check if ~/.share/local exists before trying to create a directory in there.

### ISSUE THREAD

**Issue by dongmaster** [cosarara97/fucking-weeb#5]
On a clean Windows system and cygwin installation, launching Fucking Weeb fails because it is assumed that ~/.share/local exists, but that is not the case and FW just crashes.

Is there something in CHICKEN scheme that is equivalent to ```mkdir -p```?

**Comment by cosarara** [comment]
Should be fixed with https://github.com/cosarara97/fucking-weeb/commit/f1f095a36880206181432b3c1d06871a4eb315b2
